# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20161011_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
