# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='Upload',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='downloaded',
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[upload.models.Upload.validate_file]),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
